# Generated by Django 4.0.1 on 2022-01-25 19:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerId', models.AutoField(primary_key=True, serialize=False)),
                ('UserId', models.IntegerField(default=None)),
                ('Name', models.CharField(max_length=25)),
                ('LastName', models.CharField(max_length=25)),
                ('Phone', models.CharField(max_length=9, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('DiscountId', models.AutoField(primary_key=True, serialize=False)),
                ('Percent', models.FloatField()),
                ('VisitCount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=25)),
                ('LastName', models.CharField(max_length=25)),
                ('Pesel', models.CharField(max_length=25)),
                ('Town', models.CharField(max_length=25)),
                ('HouseNumber', models.CharField(max_length=25)),
                ('Salary', models.FloatField()),
                ('Phone', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Servicee',
            fields=[
                ('ServiceeId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=40)),
                ('Price', models.IntegerField()),
                ('Time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=25, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('Pass', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('VisitId', models.AutoField(primary_key=True, serialize=False)),
                ('DiscountId', models.IntegerField(default=None)),
                ('Ddate', models.DateField()),
                ('Hhour', models.TimeField()),
                ('Status', models.CharField(max_length=2)),
                ('Customerr', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fryzjer.customer')),
                ('Employeee', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fryzjer.employee')),
                ('servicee', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fryzjer.servicee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='Userr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fryzjer.user'),
        ),
    ]
