# Generated by Django 4.0.1 on 2022-01-18 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fryzjer', '0002_rename_serviceeid_visit_serviceee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='serviceee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviceee', to='fryzjer.servicee'),
        ),
    ]
