# Generated by Django 4.0.1 on 2022-01-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fryzjer', '0002_alter_customer_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='UserId',
            field=models.IntegerField(default=None),
        ),
    ]
