# Generated by Django 4.0.1 on 2022-01-18 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fryzjer', '0003_alter_visit_serviceee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='serviceee',
        ),
        migrations.AddField(
            model_name='visit',
            name='ServiceeId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='fryzjer.servicee'),
        ),
    ]
