# Generated by Django 4.0.1 on 2022-01-18 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fryzjer', '0004_remove_visit_serviceee_visit_serviceeid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='ServiceeId',
            new_name='Service',
        ),
    ]
