# Generated by Django 4.0.1 on 2022-01-18 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fryzjer', '0007_remove_visit_servicee_visit_servicee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='servicee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fryzjer.servicee'),
        ),
    ]
