# Generated by Django 4.0.1 on 2022-01-19 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fryzjer', '0008_alter_visit_servicee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='UserId',
            new_name='user',
        ),
    ]
