# Generated by Django 4.0.1 on 2022-01-19 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fryzjer', '0009_rename_userid_visit_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='user',
            new_name='userr',
        ),
    ]
